version: '3.1'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
